config/routes.rb
Rails.application.routes.draw do

  root 'statuses#index'

  resources :statuses do
    collection do
      get 'query'
      get 'upload'
      post 'upload_csv_file'
    end
    # get 'upload', on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
    validates :object_id, :object_type, :timestamp, :state, presence: true

    def self.import_csv(csv_file)
        text = File.read(csv_file).gsub(/\\"/, '""')
        csv = CSV.parse(text)
        data = []

        csv.each do |l|
            data.push(object_id: l[0], object_type: l[1],
                      timestamp: DateTime.strptime(l[2], '%s'),
                      state: ActiveSupport::JSON.decode(l[3]))
        end

        Status.transaction do
            columns = [:object_id, :object_type, :timestamp, :state]
            Status.import columns, data, validate: false
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upload
  end

  def upload_csv_file
    file = params[:csv_file]
    # Status.import_csv file
    UploadProcessorJob.perform_later file.path
    redirect_to statuses_url, notice: 'CSV file uploaded and being processed. Please refresh'
  end

  def query
    object_type = params[:object_type]
    object_id = params[:object_id]
    @timestamp = Time.now

    if params[:ts]
      @timestamp = Time.new(params[:ts][:year].to_i,
                            params[:ts][:month].to_i,
                            params[:ts][:day].to_i,
                            params[:ts][:hour].to_i,
                            params[:ts][:minute].to_i,
                            params[:ts][:second].to_i)
    end

    statuses = Status.arel_table

    # result = Status.where(object_id: object_id,).
    result = Status.where(object_id: object_id).
                    where(statuses[:object_type].matches(object_type)).
                    where("timestamp <= ?", @timestamp).
                    order("timestamp DESC")

    # logger.debug ">>>>>>>>>>> #{result.size}, ts = #{timestamp}"

    @state_result = {}

    result.each do |s|
      @state_result = @state_result.merge(s.state)
    end

    respond_to do |format|
      format.html { render :query }
      format.json  { render json: @state_result }
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:object_id, :object_type, :timestamp, :state)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper

  def current_url(new_params)
    url_for params.permit!.merge(new_params)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Changelog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">

    <%= yield %>

    </div>

  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_for(status) do |f| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :object_id %>
    <%= f.text_field :object_id %>
  </div>

  <div class="field">
    <%= f.label :object_type %>
    <%= f.text_field :object_type %>
  </div>

  <div class="field">
    <%= f.label :timestamp %>
    <%= f.datetime_select :timestamp %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_area :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Statuses</h1>

<table>
  <thead>
    <tr>
      <th style="text-align:right">#ID</th>
      <th style="text-align:center">Type</th>
      <th>Timestamp</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.object_id %></td>
        <td><%= status.object_type %></td>
        <td><%= status.timestamp.to_formatted_s(:long) %></td>
        <td><%= status.state %></td>
        <td><%= link_to 'Show', status %></td>
        <!-- <td><%= link_to 'Edit', edit_status_path(status) %></td> -->
        <!-- <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Status', new_status_path %> -->

<%= link_to 'Query Status', query_statuses_path %>

<%= link_to 'Upload CSV', upload_statuses_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/query.html.erb
<h2> Query Status </h2>
<br/>

<%= form_tag({action: :query}, method: :get) do %>

<div class="field">
  <%= label_tag "#ID" %>
  <%= text_field_tag :object_id, params[:object_id] %>
</div>

<div class="field">
  <%= label_tag "Type" %>
  <!-- <%= text_field_tag :object_type, params[:object_type] %> -->
  <%= select_tag :object_type, options_for_select(Status.distinct.pluck(:object_type), params[:object_type]) %>
</div>

<div class="field">
  <%= label_tag "Timestamp" %>
  <%= select_datetime @timestamp, :prefix => 'ts'  %>
  <%= select_second @timestamp, :prefix => 'ts' %>
</div>

<div class="actions">
    <%= submit_tag("Query") %> or
    <%= link_to 'Back', statuses_path %>
</div>
<% end %>

<hr>

<% if @state_result.present? %>
<p class="state_display">
  <%= @state_result %>
  <span class="json_format_link">
  <%= link_to "In JSON format", current_url(:format=>:json), class: 'in_json_link' %>
  </span>
</p>
<% end %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <tbody>
    <tr>
      <td><strong>#ID:</strong></td>
      <td><%= @status.object_id %></td>
    </tr>
    <tr>
      <td><strong>Type:</strong></td>
      <td><%= @status.object_type %></td>
    </tr>
    <tr>
      <td><strong>Timestamp:</strong></td>
      <td><%= @status.timestamp %></td>
    </tr>
  </tbody>
</table>

<p>
  Last updated <%= time_ago_in_words(@status.updated_at) %>
</p>

<p class="state_display">
  <%= @status.state %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Destroy', @status, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/upload.html.erb
<h2>Upload CSV</h2>

<%= form_tag({action: :upload_csv_file}, multipart: true) do %>

<div class="field">
<%= file_field_tag 'csv_file' %>
</div>

<div class="actions">
    <%= submit_tag %>
    or 
    <%= link_to 'Cancel', statuses_path %>
</div>
<% end %>